"""Regenerate the site's code-block styles: ``site/assets/chroma-light.css`` and ``-dark.css``.

    uv run python scripts/chroma_css.py

Hugo highlights code with Chroma. ``hugo gen chromastyles`` emits one theme as class-based
CSS; the light one (``github``) is written as-is and the dark one (``github-dark``) has every
selector scoped under ``[data-theme="dark"]`` so code blocks follow the page theme. Re-run
after a Hugo upgrade. ``site/assets/site.css`` then overrides the block background with the
brand's sunken surface.
"""
from __future__ import annotations

import re
import subprocess
from pathlib import Path

ASSETS = Path(__file__).resolve().parent.parent / "site" / "assets"
HEADER = "/* Generated by scripts/chroma_css.py — do not edit. Chroma style: %s */\n"


def chromastyles(style: str) -> str:
    return subprocess.run(
        ["hugo", "gen", "chromastyles", f"--style={style}"], capture_output=True, text=True, check=True
    ).stdout


def scoped(css: str, prefix: str) -> str:
    out = []
    for line in css.splitlines():
        m = re.match(r"^(/\*.*?\*/\s*)?(\.[^{]+)(\{.*)$", line)
        if m:
            comment, sel, rest = m.group(1) or "", m.group(2).strip(), m.group(3)
            sel = ", ".join(f"{prefix} {s.strip()}" for s in sel.split(","))
            out.append(f"{comment}{sel} {rest}")
        else:
            out.append(line)
    return "\n".join(out) + "\n"


def main() -> None:
    light = ASSETS / "chroma-light.css"
    light.write_text(HEADER % "github" + chromastyles("github"))
    dark = ASSETS / "chroma-dark.css"
    dark.write_text(HEADER % 'github-dark, scoped under [data-theme="dark"]' + scoped(chromastyles("github-dark"), '[data-theme="dark"]'))
    for p in (light, dark):
        print(f"wrote {p.relative_to(ASSETS.parent.parent)} ({p.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
