"""Generate the scored-submissions table everywhere it appears, from the primary records.

    uv run python scripts/standings.py            # rewrite README.md + site/data/submissions.json
    uv run python scripts/standings.py --check    # exit 1 if either file is out of date

Inputs, both read-only:

- ``private/submissions/*.status.json`` — Arc's verbatim record per entry, written by
  ``private/research/protocol/log_submission.py`` (which runs this script afterwards).
- ``~/data/sidechain/vcc2026/leaderboards/lb_*.json`` — board snapshots, taken with
  ``python -m sidechain.eval.leaderboard``.

The one rule (Saber, 2026-08-23; board size clarified 2026-08-24): **rank-when-scored
is the rank in the first board snapshot that contains the entry, and the board size is
that snapshot's full team count** — ``live.total``, never the embedded row count. The
page embeds only its top ~50 teams and the two diverged on 2026-08-21 (95 teams, 50
embedded), which had this script quietly printing "of 50" against a 216-team board.
The board shows one row per team and re-ranks continuously, so a later look is not the
rank when scored. An entry ranked below the embed appears in no snapshot: it falls back
to its own status record's ``rank`` — Arc's number when the record was fetched, which
``log_submission.py`` fetches right after scoring — with the board size from the first
snapshot taken after the submission. Take a snapshot soon after scoring so both the
first-containing snapshot and that fallback stay honest.

Outputs, both fully generated — never edit them by hand:

- ``README.md``: the table between ``<!-- standings:begin -->`` and ``<!-- standings:end -->``.
- ``site/data/submissions.json``: the same rows for saberhq.com/sidechain (a pushed
  change under site/ redeploys the page).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
SITE_JSON = ROOT / "site" / "data" / "submissions.json"
BEGIN, END = "<!-- standings:begin -->", "<!-- standings:end -->"

# Board names predating the ADR 0005 naming scheme, keyed by build stem. Entries are
# never renamed on the board, so this map only ever grows.
ALIASES = {"r1_delta_even_v1": "SER-1"}
SERIES_RE = re.compile(r"\b([A-Z]{3}-\d+[a-z]*)\b")

# Board names that neither parse nor sit in ALIASES land here (load_rows resets it).
# The row still renders under its raw stem so old data keeps flowing, but --check fails:
# a silent fallback is how a misnamed entry would reach the README and the site unnoticed.
NAME_WARNINGS: list[str] = []

DEFAULTS = {"deadline": "2026-11-05", "final_test_set": "2026-10-22"}
ABOUT = (
    "Generated by scripts/standings.py from private/submissions/*.status.json and the board "
    "snapshots in ~/data/sidechain/vcc2026/leaderboards/ — do not edit by hand; run the script "
    "(log_submission.py runs it after recording an entry). rank is from the first snapshot "
    "that contains the entry (the board re-ranks continuously, so a later look is not the rank "
    "when scored) and teams is that snapshot's full team count, not the ~50 rows the page "
    "embeds; an entry below the embed takes its status record's scoring-time rank. The README "
    "table between the standings markers is the same rows."
)


def series_name(model_name: str, stem: str) -> str:
    m = SERIES_RE.search(model_name or "")
    if m:
        return m.group(1)
    return ALIASES.get(stem, stem)


def _snapshot_stamp(iso_date: str) -> str:
    """An ISO submission date as a snapshot-filename stamp (YYYYMMDDTHHMMZ), for ordering."""
    d = iso_date or ""
    return f"{d[:4]}{d[5:7]}{d[8:10]}T{d[11:13]}{d[14:16]}Z" if len(d) >= 16 else ""


def load_rows(subs_dir: Path, snaps_dir: Path) -> list[dict]:
    NAME_WARNINGS.clear()
    snapshots = []
    for f in sorted(snaps_dir.glob("lb_*.json")):
        d = json.loads(f.read_text())
        live = d.get("live", {})
        entries = live.get("entries", [])
        snapshots.append({
            "stamp": d.get("fetched_utc", ""),
            "ranks": {e["id"]: e["rank"] for e in entries},
            # The page embeds only its top ~50 teams; `total` is the whole field.
            # Old snapshots that predate the divergence have total == len(entries).
            "teams": live.get("total") or len(entries),
        })

    rows = []
    for f in sorted(subs_dir.glob("*.status.json")):
        s = json.loads(f.read_text())
        if s.get("score_avg") is None:
            continue  # failed or unscored submissions stay out of the table
        stem = f.name.split("_", 1)[1].removesuffix(".status.json")
        rank = teams = None
        for snap in snapshots:
            if s["entry_id"] in snap["ranks"]:
                rank, teams = snap["ranks"][s["entry_id"]], snap["teams"]
                break
        if rank is None and s.get("rank") is not None:
            # Ranked below the embed, so no snapshot will ever contain it. The
            # status record carries Arc's rank at fetch time (log_submission.py
            # fetches right after scoring); board size from the first snapshot
            # after the submission — the closest witness to the field it ranked in.
            rank = s["rank"]
            submitted = _snapshot_stamp(s.get("submission_date") or "")
            teams = next((sn["teams"] for sn in snapshots if sn["stamp"] >= submitted), None)
        if not SERIES_RE.search(s.get("model_name") or "") and stem not in ALIASES:
            NAME_WARNINGS.append(
                f"{f.name}: board name {(s.get('model_name') or '(none)')!r} carries no "
                "series name and the stem has no ALIASES entry -- falling back to the raw "
                "stem; add the alias or fix the record (ADR 0005)")
        # Two entries reached the board before cards were required (ADR 0005) and the
        # board cannot be backfilled -- a `<record>.card.txt` beside the status record
        # supplies the card for OUR surfaces only, flagged so the site labels it.
        card = (s.get("description") or "").strip()
        card_retro = False
        if not card:
            side = f.with_name(f.name.replace(".status.json", ".card.txt"))
            if side.exists():
                card, card_retro = side.read_text().strip(), True
        rows.append({
            "_submitted": s.get("submission_date") or "",
            "date": (s.get("submission_date") or "")[:10],
            "name": series_name(s.get("model_name", ""), stem),
            "board_name": s.get("model_name") or stem,
            "overall": round(s["score_avg"], 4),
            "rank": rank,
            "teams": teams,
            "card": card,
            "card_retro": card_retro,
        })
    rows.sort(key=lambda r: r.pop("_submitted"))  # submission order; the key leaves the output
    return rows


def rank_label(rank, teams) -> str:
    return (f"#{rank} of {teams}" if teams else f"#{rank}") if rank else "—"


def readme_block(rows: list[dict]) -> str:
    out = ["| date (UTC) | submission | overall | rank when scored |", "|---|---|---|---|"]
    for r in rows:
        sub = f"`{r['board_name']}`"
        if r["name"] not in r["board_name"]:
            sub += f" (`{r['name']}`)"
        out.append(f"| {r['date']} | {sub} | {r['overall']:.4f} | {rank_label(r['rank'], r['teams'])} |")
    return "\n".join(out)


def render(rows: list[dict]) -> tuple[str, str]:
    """(new README text, new site JSON text)."""
    text = README.read_text()
    if BEGIN not in text or END not in text:
        sys.exit(f"README.md is missing the {BEGIN} / {END} markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    readme = f"{head}{BEGIN}\n{readme_block(rows)}\n{END}{tail}"

    keep = DEFAULTS | {
        k: v for k, v in (json.loads(SITE_JSON.read_text()) if SITE_JSON.exists() else {}).items()
        if k in DEFAULTS
    }
    payload = {"_about": ABOUT, **keep, "entries": rows}
    return readme, json.dumps(payload, indent=2) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--submissions", type=Path, default=ROOT / "private" / "submissions")
    ap.add_argument("--snapshots", type=Path,
                    default=Path.home() / "data" / "sidechain" / "vcc2026" / "leaderboards")
    ap.add_argument("--check", action="store_true", help="report drift instead of writing")
    args = ap.parse_args()

    rows = load_rows(args.submissions, args.snapshots)
    if not rows:
        sys.exit("no scored submissions found — refusing to write empty tables")
    for w in NAME_WARNINGS:
        print(f"warning: {w}", file=sys.stderr)
    readme, site = render(rows)

    drift = []
    if readme != README.read_text():
        drift.append("README.md")
    if not SITE_JSON.exists() or site != SITE_JSON.read_text():
        drift.append("site/data/submissions.json")
    if args.check:
        print(f"{len(rows)} scored entries; " + (f"OUT OF DATE: {', '.join(drift)}" if drift else "both outputs current"))
        return 1 if drift or NAME_WARNINGS else 0
    README.write_text(readme)
    SITE_JSON.write_text(site)
    for r in rows:
        print(f"{r['date']}  {r['name']:8s} {r['overall']:.4f}  {rank_label(r['rank'], r['teams'])}")
    print(f"wrote README.md + site/data/submissions.json ({len(rows)} rows"
          + (f"; updated: {', '.join(drift)})" if drift else "; no change)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
