"""Generate the scored-submissions table everywhere it appears, from the primary records.

    uv run python scripts/standings.py            # rewrite README.md + site/data/submissions.json
    uv run python scripts/standings.py --check    # exit 1 if either file is out of date

Inputs, both read-only:

- ``private/submissions/*.status.json`` — Arc's verbatim record per entry, written by
  ``private/research/protocol/log_submission.py`` (which runs this script afterwards).
- ``~/data/sidechain/vcc2026/leaderboards/lb_*.json`` — board snapshots, taken with
  ``python -m sidechain.eval.leaderboard``.

The one rule (Saber, 2026-08-23): **rank-when-scored is the rank in the first board
snapshot that contains the entry, and the board size is that snapshot's team count.**
The board shows one row per team and re-ranks continuously, so a status record's own
``rank`` field is only "the rank when someone last looked" — it is never used for
display. An entry that appears in no snapshot gets an em-dash; take a snapshot soon
after scoring so that stays rare.

Outputs, both fully generated — never edit them by hand:

- ``README.md``: the table between ``<!-- standings:begin -->`` and ``<!-- standings:end -->``.
- ``site/data/submissions.json``: the same rows for saberhq.com/sidechain (a pushed
  change under site/ redeploys the page).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
SITE_JSON = ROOT / "site" / "data" / "submissions.json"
BEGIN, END = "<!-- standings:begin -->", "<!-- standings:end -->"

# Board names predating the ADR 0005 naming scheme, keyed by build stem. Entries are
# never renamed on the board, so this map only ever grows.
ALIASES = {"r1_delta_even_v1": "SER-1"}
SERIES_RE = re.compile(r"\b([A-Z]{3}-\d+[a-z]*)\b")

DEFAULTS = {"deadline": "2026-11-05", "final_test_set": "2026-10-22"}
ABOUT = (
    "Generated by scripts/standings.py from private/submissions/*.status.json and the board "
    "snapshots in ~/data/sidechain/vcc2026/leaderboards/ — do not edit by hand; run the script "
    "(log_submission.py runs it after recording an entry). rank/teams are the first snapshot "
    "that contains the entry: the board re-ranks continuously, so a later look is not the rank "
    "when scored. The README table between the standings markers is the same rows."
)


def series_name(model_name: str, stem: str) -> str:
    m = SERIES_RE.search(model_name or "")
    if m:
        return m.group(1)
    return ALIASES.get(stem, stem)


def load_rows(subs_dir: Path, snaps_dir: Path) -> list[dict]:
    snapshots = []
    for f in sorted(snaps_dir.glob("lb_*.json")):
        d = json.loads(f.read_text())
        entries = d.get("live", {}).get("entries", [])
        snapshots.append({e["id"]: e["rank"] for e in entries} | {"__teams__": len(entries)})

    rows = []
    for f in sorted(subs_dir.glob("*.status.json")):
        s = json.loads(f.read_text())
        if s.get("score_avg") is None:
            continue  # failed or unscored submissions stay out of the table
        stem = f.name.split("_", 1)[1].removesuffix(".status.json")
        rank = teams = None
        for snap in snapshots:
            if s["entry_id"] in snap:
                rank, teams = snap[s["entry_id"]], snap["__teams__"]
                break
        rows.append({
            "_submitted": s.get("submission_date") or "",
            "date": (s.get("submission_date") or "")[:10],
            "name": series_name(s.get("model_name", ""), stem),
            "board_name": s.get("model_name") or stem,
            "overall": round(s["score_avg"], 4),
            "rank": rank,
            "teams": teams,
        })
    rows.sort(key=lambda r: r.pop("_submitted"))  # submission order; the key leaves the output
    return rows


def readme_block(rows: list[dict]) -> str:
    out = ["| date (UTC) | submission | overall | rank when scored |", "|---|---|---|---|"]
    for r in rows:
        sub = f"`{r['board_name']}`"
        if r["name"] not in r["board_name"]:
            sub += f" (`{r['name']}`)"
        rank = f"#{r['rank']} of {r['teams']}" if r["rank"] else "—"
        out.append(f"| {r['date']} | {sub} | {r['overall']:.4f} | {rank} |")
    return "\n".join(out)


def render(rows: list[dict]) -> tuple[str, str]:
    """(new README text, new site JSON text)."""
    text = README.read_text()
    if BEGIN not in text or END not in text:
        sys.exit(f"README.md is missing the {BEGIN} / {END} markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    readme = f"{head}{BEGIN}\n{readme_block(rows)}\n{END}{tail}"

    keep = DEFAULTS | {
        k: v for k, v in (json.loads(SITE_JSON.read_text()) if SITE_JSON.exists() else {}).items()
        if k in DEFAULTS
    }
    payload = {"_about": ABOUT, **keep, "entries": rows}
    return readme, json.dumps(payload, indent=2) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--submissions", type=Path, default=ROOT / "private" / "submissions")
    ap.add_argument("--snapshots", type=Path,
                    default=Path.home() / "data" / "sidechain" / "vcc2026" / "leaderboards")
    ap.add_argument("--check", action="store_true", help="report drift instead of writing")
    args = ap.parse_args()

    rows = load_rows(args.submissions, args.snapshots)
    if not rows:
        sys.exit("no scored submissions found — refusing to write empty tables")
    readme, site = render(rows)

    drift = []
    if readme != README.read_text():
        drift.append("README.md")
    if not SITE_JSON.exists() or site != SITE_JSON.read_text():
        drift.append("site/data/submissions.json")
    if args.check:
        print(f"{len(rows)} scored entries; " + (f"OUT OF DATE: {', '.join(drift)}" if drift else "both outputs current"))
        return 1 if drift else 0
    README.write_text(readme)
    SITE_JSON.write_text(site)
    for r in rows:
        rank = f"#{r['rank']} of {r['teams']}" if r["rank"] else "—"
        print(f"{r['date']}  {r['name']:8s} {r['overall']:.4f}  {rank}")
    print(f"wrote README.md + site/data/submissions.json ({len(rows)} rows"
          + (f"; updated: {', '.join(drift)})" if drift else "; no change)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
